### ISSUE TITLE
Override detected version

### ISSUE THREAD

**Issue by Lioness100** [fabiospampinato/tiny-bin#2]
The README says that this package will automatically detect a version from package.json- is there a way to overwrite this, maybe a `.version('...')` method?

**Comment by fabiospampinato** [comment]
There is no API for that. Does the automatic detection not work well enough?

**Comment by Lioness100** [comment]
A few reasons a method might be helpful from the top of my head:

- Binary distribution: If a CLI is compiled into a binary, it might not have access to the package.json file and therefore, cannot automatically detect the version.
- Testing: During testing, it may be necessary to set a specific version for the CLI to simulate different scenarios.
- Independent versioning: If there are multiple CLIs in a project, it may be necessary to set versions independently of each other.
- Automated versioning: In certain cases, it may be desirable to set the version automatically based on certain conditions, such as a build number or date.

It doesn't seem like it would be too hard to add, would it?

**Comment by fabiospampinato** [comment]
Seems reasonable. I added a `.package` function in v1.1.0. Thanks for the suggestion.

**Comment by Lioness100** [comment]
Thanks!!
